use_default_settings: true

server:
  bind_address: "0.0.0.0"
  port: 8080
  secret_key: "ariadne-local-dev-change-me"
  limiter: false
  image_proxy: false

search:
  formats:
    - html
    - json

outgoing:
  request_timeout: 6.0